name: Logger Push

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push-logger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit and push logger file
        run: |
          git config --global user.name "BarberBot"
          git config --global user.email "barberbot@users.noreply.github.com"
          git add data/barber_logger.csv
          git commit -m "📈 Update logger file" || echo "No changes to commit"
          git push
